### ISSUE TITLE
Ubuntu 22.04 make error

### ISSUE THREAD

**Issue by bipul-mohanto** [NVIDIA/OptiX_Apps#11]
#### System Overview: 
* OS: Ubuntu 22.04
* cmake version 3.22.1
* GNU Make 4.3
* NVIDIA-SMI 515.48.07    
* Driver Version: 515.48.07    
* CUDA Version: 11.7  
* Build cuda_11.7.r11.7/compiler.31294372_0
* GPU: NVIDIA RTX 3090
* gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0

#### Approach:
* Installed required libraries: `sudo apt-get install -y libglfw3-dev libglew-dev libdevil-dev libassimp-dev libdart-external-imgui-dev libimgui-dev`
* Cloned: `git clone --recursive https://github.com/NVIDIA/OptiX_Apps.git`
* I am using OptiX 7.3, that is in Download folder, `OptiX_Apps` is also in the same folder
* Followed the build instructions until `cmake` (both are working fine), 
  * `cmake .. `
  * `OPTIX73_PATH=~/Downloads/NVIDIA-OptiX-SDK-7.3.0-linux64-x86_64 cmake ..`  
* **Problem: `make / make -j 8` is not working** returning following errors:

```javascript
/usr/bin/ld: CMakeFiles/rtigo3.dir/imgui/imgui_impl_glfw_gl3.cpp.o: undefined reference to symbol 'glEnable'
/usr/bin/ld: /lib/x86_64-linux-gnu/libGL.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [apps/rtigo3/CMakeFiles/rtigo3.dir/build.make:824: bin/rtigo3] Error 1
make[1]: *** [CMakeFiles/Makefile2:307: apps/rtigo3/CMakeFiles/rtigo3.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

I could not figure out what I am doing wrong. Could you suggest any solution?

**Comment by droettger** [comment]
If there is an undefined reference to a core OpenGL entry point function, that would mean the OpenGL import library is missing from the linker command line.

The first package required in all these example's CMakeLists.txt is
`find_package(OpenGL REQUIRED)`
and it's added to the linked libraries here:
```
target_link_libraries( rtigo3
  ${OPENGL_gl_LIBRARY}
```
Maybe add a message printing that CMake value to see if it's set correctly.

Are all examples failing to build or only a subset?

The only UNIX specific setting in the CMakeLists.txt is this at the end to be able to dynamically load libraries with dlopen.
```
if (UNIX)
  target_link_libraries( rtigo3 dl )
endif()

```
I had been building the examples with CMake 3.22.1 under Windows, so I doubt it's related to the CMake version used.

**Comment by bipul-mohanto** [comment]
I also just have figured it out, it was `OpenGL linking error` for all examples. Adding the following line in each CMakeLists.txt has solved the problem for now:  

```
include_directories( ${OPENGL_INCLUDE_DIRS} )
target_link_libraries(${project_name} ${OPENGL_LIBRARIES}  )

```

**Comment by bipul-mohanto** [comment]
intro_runtime in **Debug** mode returning following error in line (Release Mode is running fine):

https://github.com/NVIDIA/OptiX_Apps/blob/1dea1aa837691d28d4e9f05c8cdbfd75199ec47e/apps/intro_runtime/src/Texture.cpp#L986

**error message:** `Process finished with exit code 132 (interrupted by signal 4: SIGILL)`

**Comment by droettger** [comment]
On the OpenGL error: 
What do the `${OPENGL_gl_LIBRARY}` and the `${OPENGL_LIBRARIES}` and `${OPENGL_INCLUDE_DIRS}` contain in your case?
When I'm going to update the examples to OptiX 7.5.0, I want to fix these issues.

About the texture object crash in debug:
Was there any warning about missing texture files on the console?
Did you copy all files from the data folder into the executable folder?
When running from inside a debugger, was the working directory set to the module directory?

See the places marked with **IMPORTANT** inside the README.md
https://github.com/NVIDIA/OptiX_Apps/blob/master/README.md

**Comment by bipul-mohanto** [comment]
```diff
find_package(OpenGL REQUIRED)
...
+include_directories(${OPENGL_INCLUDE_DIRS})
...
target_link_libraries( intro_driver # for each of the sample project 
- ${OPENGL_gl_LIBRARY} # commented this and replaced with ${OPENGL_LIBRARIES} 
+ ${OPENGL_LIBRARIES} 
)
```

**Comment by bipul-mohanto** [comment]
Regarding the texture object crash in debug, 
I am using **CLion IDE**. 
- [x] copied all files from the data folder into the executable folder
- [x] changed the working directory set to the module directory (`debug/release-bin`)

Warning about missing texture files on the console:
**Debug:** 
```cpp
/home/highvive1/Downloads/OptiX_Apps/cmake-build-debug/bin/intro_runtime
ERROR: /home/highvive1/Downloads/OptiX_Apps/apps/intro_runtime/src/Texture.cpp(986): cudaCreateTextureObject(&m_textureObject, &resourceDescription, &m_textureDescription, nullptr) failed with code 1: invalid argument

Process finished with exit code 132 (interrupted by signal 4: SIGILL)
```

**Release**
```cpp
ERROR Picture::load(): ./slots_alpha.png not loaded
ERROR: /home/highvive1/Downloads/OptiX_Apps/apps/intro_runtime/src/Texture.cpp(986): cudaCreateTextureObject(&m_textureObject, &resourceDescription, &m_textureDescription, nullptr) failed with code 1: invalid argument
ERROR Picture::load(): ./NVIDIA_Logo.jpg not loaded
ERROR: /home/highvive1/Downloads/OptiX_Apps/apps/intro_runtime/src/Texture.cpp(986): cudaCreateTextureObject(&m_textureObject, &resourceDescription, &m_textureDescription, nullptr) failed with code 1: invalid argument
```

I did not notice this before, I think the devil library is not working perfectly during `release`. 

![Screenshot from 2022-07-07 17-57-34](https://user-images.githubusercontent.com/12484581/177819312-6eaa041e-2046-4698-bfc4-2c010fe325c4.png)

**Comment by droettger** [comment]
I know where I would need to change the CMake scripts.
My question was what they actually contain on your system, so what the CMake output of these messages are:
```
message("OPENGL_gl_LIBRARY= " "${OPENGL_gl_LIBRARY}")
message("OPENGL_INCLUDE_DIRS= " "${OPENGL_INCLUDE_DIRS}")
message("OPENGL_LIBRARIES= " "${OPENGL_LIBRARIES}")
```

See https://github.com/NVIDIA/OptiX_Apps/blob/master/apps/rtigo3/CMakeLists.txt#L230

I had have these examples tested under Linux in the past and they worked, so I would need to understand the changes which let them fail on your newer system.

On the CUDA error, I have not used CUDA 11.7 to build these examples, yet. 
They worked fine with CUDA 10.1 to 11.5 on my Windows systems.

No idea what is wrong with the texture loading on your system. If the Picture::load() fails, that is usually due to not finding the file, which are searched relative to the executable. So if the slots_alpha.png and NVIDIA_Logo.jpg files are inside the executable folder and still don't get loaded, then I cannot say what's going wrong.
Irrespective of the Picture::load() failure there should be a red-green-blue-yellow 2x2 dummy RGBA8 texture built as stand-in, but since your CUDA texture object creation fails, that's also not shown.

It will take me some time to work on that and have them checked under Linux.

**Comment by bipul-mohanto** [comment]
Sorry, I am just a newbie both in graphics and linux, do not know much how everything is working. I just install your project to learn OptiX. I think your code base has the best explanation for different optix functions. For now I would like to ignore the texture issue, that is not a big deal for me. I start studying `intro_drover` example. Later I will come back and fix these texture issues. :) Thanks for this code repository.

**Comment by droettger** [comment]
I could reproduce the random cudaCreateTextureObject() failures in the intro_runtime example when using CUDA 11.7.
The commit adding Visual Studio 2022 support contains a fix for that part.

**Comment by bipul-mohanto** [comment]
This updated `Texture.cpp` solved the previous error of loading texture like a magic:  


![Screenshot from 2022-08-12 19-17-09](https://user-images.githubusercontent.com/12484581/184410693-fcf3ad03-967e-478d-ac78-4564ab200f42.png)
