### ISSUE TITLE
Debug versions fail in VS 2019 environment

### ISSUE THREAD

**Issue by kyamant** [NVIDIA/OptiX_Apps#4]
Release versions work both within VS2019 and stand-alone.
Debug versions fail in both cases; just a window opens then closes

**Comment by droettger** [comment]
I always develop in debug mode and this should not happen when following all **Build** and **Run** instructions from the `README.md`.

This will happen for the intro examples when they don't find the required texture image files. These need to be copied from the` data` folder next to the executable. If you did that in the release mode target, you need to do that for the debug target as well.

(I'm going to add an error output when required files are not found.)

**Comment by kyamant** [comment]
Thanks
