### ISSUE TITLE
rtigo3.exe malware???

### ISSUE THREAD

**Issue by kyamant** [NVIDIA/OptiX_Apps#5]
Kaspersky Virus Removal Tool reports rtigo3.exe as a virus
![Untitled](https://user-images.githubusercontent.com/16941640/128149140-bceac8cb-bbfc-4ea8-ae46-ec85cf483faa.png)

**Comment by droettger** [comment]
Never heard that before and we've been running different anti-virus programs inside the company.

You've built that executable from sources yourself. It's also strange that only one of six examples is flagged. nvlink_shared is derived from rtigo3 and just uses fewer rendering strategies and all examples use the same libraries.

So either Kaspersky is wrong, or your system is already infected elsewhere, or one of the third party binary libraries is infected but then all examples should have been flagged.

I would recommend wiping the build folder and emptying the Recycle Bin, then run the virus detection manually on your whole system, and if that didn't find anything, rebuild the examples from scratch.

If that still triggers Kaspersky, there is nothing I can do about that.
Searching the web, there have been similar false positives been reported in completely unrelated development environments.
You would need to get in contact with Kaspersky's support then.

**Comment by kyamant** [comment]
Curiously enough, it is only the debug version, release passes fine.
D:\Personal\Projects\ProjOptiX7Apps\build\bin\Debug\rtigo3.exe
Trojan program
    MD5:  6C3EC7C4920BAB71CF54500B953961C1
    SHA256:  7FB9193C922C465817B5F0687D8774257133A6F7EF1D109F4E7A511C85C285A9

**Comment by droettger** [comment]
If Kaspersky scans for specific byte patterns and these happen to appear inside executables you built, then this is a false positive like here:
https://community.kaspersky.com/kaspersky-internet-security-13/vho-trojan-win32-convagent-gen-detected-when-trying-to-compile-c-codeblocks-17604

This is not a problem inside these OptiX 7 examples. I'm closing this now.
