### ISSUE TITLE
more realistic shadow render

### ISSUE THREAD

**Issue by ypwang61** [NVIDIA/OptiX_Apps#7]
Hello, thanks to your optix7course and Optix_Apps's guiding, I can try some simple but cool examples, but if I want to render scenes with  
 glass and hope to get realistic shadow, maybe I need to consider more about the absorbtion since to distanct travelling in the glass and the Fresnel Effect？ Which part of code maybe needed to change for this? Thanks a lot for your help.
The following is the shadow picture from rtigo3
![image](https://user-images.githubusercontent.com/85465837/145672012-c9a0c5d0-a1a4-4d58-8945-37b1edc7618f.png)

**Comment by droettger** [comment]
>maybe I need to consider more about the absorbtion since to distanct travelling in the glass and the Fresnel Effect？

Both are already implemented. Search the source code for "Fresnel" and "absorption".

Read this code which implements the glass material:
https://github.com/NVIDIA/OptiX_Apps/blob/master/apps/rtigo3/shaders/bxdf_specular.cu#L94

Returning the traveled distance happens here:
https://github.com/NVIDIA/OptiX_Apps/blob/master/apps/rtigo3/shaders/closesthit.cu#L165

The calculation for absorption in homogeneous volumes happens here:
https://github.com/NVIDIA/OptiX_Apps/blob/master/apps/rtigo3/shaders/raygeneration.cu#L91

The intro_* examples show that with the two nested cube and sphere objects which use a blue water and a green glass material.
The necessary parameters to control either are exposed inside the GUI.
