### ISSUE TITLE
intro_driver: HitRadianceCutout

### ISSUE THREAD

**Issue by kyamant** [NVIDIA/OptiX_Apps#8]
In Application.cpp, the `programGroupHitRadianceCutout` is not included in `std::vector<OptixProgramGroup> programGroups;`

**Comment by droettger** [comment]
Thanks for the report. I just fixed that inside all intro examples. Strange that it worked nonetheless.
I recommend using the less manual initialization done in the more advanced examples rtigo3 and nvlink_shared which handle the program groups a little differently.
